(function () {
  'use strict';
  var params=new URLSearchParams(location.search), id=params.get('id');
  var record=window.FACHINFO_DATEN&&window.FACHINFO_DATEN[id], content=document.querySelector('#fachinfo-content'), status=document.querySelector('#fachinfo-status'), main=document.querySelector('#fachinfo-main');
  var lab=document.querySelector('#experiment-lab'), htmlEditor=document.querySelector('#lab-html'), cssEditor=document.querySelector('#lab-css'), preview=document.querySelector('#lab-preview'), labStatus=document.querySelector('#lab-status'), controlsRoot=document.querySelector('#lab-controls');
  var config, baseHtml='', baseCss='', activePreset='calm';
  var presets={calm:'body { background:#f4f7f8; color:#203746; }',contrast:'body { background:#0b1725; color:#f6fbff; }',compact:'body { font-size:14px; } .demo-target, body > * { padding:.5rem !important; margin:.5rem !important; }'};
  if(!record){status.textContent='Die angeforderte Fachinformation wurde nicht gefunden.';document.querySelector('.fachinfo-back').hidden=false;}else{content.innerHTML=record.extra;var detail=document.createElement('section');detail.className='fachinfo-detail';detail.setAttribute('aria-label','Syntax und Beispiele');detail.innerHTML=record.detail;content.appendChild(detail);var heading=content.querySelector('h2');document.title=(heading?heading.textContent:'Fachinformation')+' · HTML';status.remove();if(record.lab)setup(record.lab);}
  if(!window.opener){document.querySelector('.fachinfo-back').hidden=false;document.querySelector('#fachinfo-close').textContent='Zur HTML-Tag-Übersicht';}
  document.querySelector('#fachinfo-close').addEventListener('click',function(){if(!window.opener){window.location.href='index.html';return;}window.close();setTimeout(function(){if(!window.closed)document.querySelector('.fachinfo-back').hidden=false;},150);});main.focus();
  function cleanHtml(value){return value.replace(/<(p|div|span|strong)([^>]*)>\s*&lt;\/?[a-z][^&]*&gt;\s*<\/\1>/gi,'').trim();}
  function previewSafe(html,css){if(/<\s*(script|iframe|object|embed|base)\b|\son[a-z]+\s*=|javascript\s*:/i.test(html)||/@import|url\s*\(\s*["']?\s*(?:https?:|\/\/|data:)/i.test(css)){labStatus.textContent='Skripte und externe Ressourcen sind in der Vorschau nicht erlaubt.';return;}var policy="default-src 'none'; style-src 'unsafe-inline'; img-src data:; font-src 'none'; media-src 'none'; connect-src 'none'; frame-src 'none'";preview.srcdoc='<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="'+policy+'"><style>*,*::before,*::after{box-sizing:border-box}body{margin:0;padding:1rem;font-family:Arial,sans-serif;color:#172331}'+css+'</style></head><body>'+html+'</body></html>';labStatus.textContent='Vorschau aktualisiert.';}
  function target(){if(config.tag==='nav')return 'nav';if(config.tag==='img')return '.demo-image, img';if(/^(input|select|textarea|button|label|form)$/.test(config.tag))return '.demo-target, '+config.tag;return '.demo-target, body > '+config.tag;}
  function enhancedControls(){var original=(config.controls||[]).map(function(x){return Object.assign({group:'Grundlagen',selector:target()},x);});if(['head','meta','title','link','style','script'].indexOf(config.tag)>=0)return original;var extra=[
    {group:'Farben',label:'Textfarbe',kind:'color',key:'color',value:'#17384a'},
    {group:'Farben',label:'Hintergrundfarbe',kind:'color',key:'background-color',value:'#eef8fa'},
    {group:'Rahmen und Rundung',label:'Rahmenfarbe',kind:'color',key:'border-color',value:'#007f95'},
    {group:'Rahmen und Rundung',label:'Rahmenstärke',kind:'range',key:'border-width',value:2,min:0,max:12,unit:'px'},
    {group:'Rahmen und Rundung',label:'Rahmenart',kind:'select',key:'border-style',value:'solid',options:[['solid','Durchgezogen'],['dashed','Gestrichelt'],['dotted','Gepunktet']]},
    {group:'Rahmen und Rundung',label:'Rundung',kind:'range',key:'border-radius',value:8,min:0,max:32,unit:'px'},
    {group:'Abstände',label:'Innenabstand',kind:'range',key:'padding',value:16,min:0,max:48,unit:'px'},
    {group:'Typografie',label:'Schriftgröße',kind:'range',key:'font-size',value:16,min:12,max:32,unit:'px'}
  ];if(config.tag==='img')extra=extra.filter(function(x){return x.key!=='color'&&x.key!=='font-size'&&x.key!=='padding';}).concat([{group:'Layout',label:'Breite',kind:'range',key:'width',value:70,min:20,max:100,unit:'%'},{group:'Layout',label:'Darstellung',kind:'select',key:'object-fit',value:'cover',options:[['cover','Ausfüllen'],['contain','Einpassen'],['fill','Strecken']]}]);if(config.tag==='nav'||config.tag==='footer')extra.push({group:'Abstände',label:'Elementabstand',kind:'range',key:'gap',value:12,min:0,max:40,unit:'px'});var seen={};return original.concat(extra).filter(function(x){var k=x.selector+'|'+x.key;if(seen[k])return false;seen[k]=true;return true;});}
  function setRule(control,value){var marker='/* Laborsteuerung: '+control.key+' */', escaped=control.key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'), pattern=new RegExp('/\\* Laborsteuerung: '+escaped+' \\*/[^\\n]*','g'), line=marker+' '+(control.selector||target())+' { '+control.key+': '+value+'; }';cssEditor.value=pattern.test(cssEditor.value)?cssEditor.value.replace(pattern,line):cssEditor.value+'\n'+line;previewSafe(htmlEditor.value,cssEditor.value);}
  function initialControlCss(){return enhancedControls().map(function(control){return '/* Laborsteuerung: '+control.key+' */ '+(control.selector||target())+' { '+control.key+': '+control.value+(control.unit||'')+'; }';}).join('\n');}
  function renderControls(){controlsRoot.replaceChildren();var groups={};enhancedControls().forEach(function(control){(groups[control.group]||(groups[control.group]=[])).push(control);});Object.keys(groups).forEach(function(name,index){var box=document.createElement('details');box.className='lab-control-group';box.open=index<2;var summary=document.createElement('summary');summary.textContent=name;var body=document.createElement('div');body.className='lab-control-group-body';groups[name].forEach(function(control){var label=document.createElement('label');label.append(document.createTextNode(control.label));var input;if(control.kind==='select'){input=document.createElement('select');control.options.forEach(function(o){input.add(new Option(o[1],o[0]));});}else{input=document.createElement('input');input.type=control.kind;if(control.min!==undefined)input.min=control.min;if(control.max!==undefined)input.max=control.max;}input.value=control.value;input.dataset.initial=control.value;var output=document.createElement('output');output.value=String(control.value)+(control.unit||'');input.addEventListener(control.kind==='select'?'change':'input',function(){var value=input.value+(control.unit||'');output.value=value;setRule(control,value);});label.append(input);if(control.kind==='range')label.append(output);body.append(label);});box.append(summary,body);controlsRoot.append(box);});}
  function setChoice(selector,key,value){document.querySelectorAll(selector).forEach(function(button){var on=button.dataset[key]===value;button.classList.toggle('is-active',on);button.setAttribute('aria-pressed',String(on));});}
  function presetCss(name){return '\n/* Laborpreset: Start */\n'+presets[name]+'\n/* Laborpreset: Ende */';}
  function selectPreset(name){activePreset=name;setChoice('[data-lab-preset]','labPreset',name);cssEditor.value=cssEditor.value.replace(/\n?\/\* Laborpreset: Start \*\/[\s\S]*?\/\* Laborpreset: Ende \*\//,'')+presetCss(name);previewSafe(htmlEditor.value,cssEditor.value);}
  function setup(value){config=value;baseHtml=cleanHtml(value.html);baseCss=value.css;lab.hidden=false;document.querySelector('#lab-title').textContent=value.title;document.querySelector('#lab-description').textContent=value.description;document.querySelector('#lab-hints').innerHTML=value.hints.map(function(h){return '<li>'+h.replace(/</g,'&lt;').replace(/>/g,'&gt;')+'</li>';}).join('');htmlEditor.value=baseHtml;cssEditor.value=baseCss+'\n'+initialControlCss();baseCss=cssEditor.value;renderControls();selectPreset('calm');}
  document.querySelector('#lab-run').addEventListener('click',function(){previewSafe(htmlEditor.value,cssEditor.value);});
  document.querySelector('#lab-reset').addEventListener('click',function(){htmlEditor.value=baseHtml;cssEditor.value=baseCss;renderControls();document.querySelector('#lab-preview-shell').className='lab-preview-shell wide';setChoice('[data-lab-width]','labWidth','wide');selectPreset('calm');labStatus.textContent='Ausgangszustand wiederhergestellt.';});
  document.querySelectorAll('[data-lab-width]').forEach(function(button){button.addEventListener('click',function(){setChoice('[data-lab-width]','labWidth',button.dataset.labWidth);document.querySelector('#lab-preview-shell').className='lab-preview-shell '+button.dataset.labWidth;});});
  document.querySelectorAll('[data-lab-preset]').forEach(function(button){button.addEventListener('click',function(){selectPreset(button.dataset.labPreset);});});
  document.querySelector('#lab-copy').addEventListener('click',function(){function fallbackCopy(){cssEditor.focus();cssEditor.select();labStatus.textContent='CSS ist markiert. Mit Strg+C (macOS: Cmd+C) kopieren.';}if(!navigator.clipboard||typeof navigator.clipboard.writeText!=='function'){fallbackCopy();return;}navigator.clipboard.writeText(cssEditor.value).then(function(){labStatus.textContent='CSS wurde kopiert.';}).catch(fallbackCopy);});
}());
